sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bixlermm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bixlermm/docker-react npm run test